version: "3"
services:
  react-app:
    build:
      context: .
    container_name: country-details-app
    image: country-details
    ports:
      - "3001:3000"
    # We are mounting our code in a volume so that we can sync our changes with the container while developing.
    volumes:
      - ./:/app/
