version: "3"
services:
  react-app:
    build:
      context: .
    container_name: country-details-app
    image: app-dev
    ports:
      - "3001:3000"
    # stdin_open:true | docker-compose file to start in an interactive mode.
    stdin_open: true
    # We are mounting our code in a volume so that we can sync our changes with the container while developing.
    volumes:
      - ./:/app/
